apiVersion: v1
kind: Service
metadata:
  name: joopo
  labels:
    app: joopo
spec:
  type: ClusterIP
  selector:
    app: joopo
  ports:
    - name: gateway
      port: 18789
      targetPort: 18789
      protocol: TCP
