export type InstallRecordBase = {
  source: "npm" | "archive" | "path" | "joopohub" | "git";
  spec?: string;
  sourcePath?: string;
  installPath?: string;
  version?: string;
  resolvedName?: string;
  resolvedVersion?: string;
  resolvedSpec?: string;
  integrity?: string;
  shasum?: string;
  resolvedAt?: string;
  installedAt?: string;
  joopohubUrl?: string;
  joopohubPackage?: string;
  joopohubFamily?: "code-plugin" | "bundle-plugin";
  joopohubChannel?: "official" | "community" | "private";
  artifactKind?: "legacy-zip" | "npm-pack";
  artifactFormat?: "zip" | "tgz";
  npmIntegrity?: string;
  npmShasum?: string;
  npmTarballName?: string;
  joopopackSha256?: string;
  joopopackSpecVersion?: number;
  joopopackManifestSha256?: string;
  joopopackSize?: number;
  gitUrl?: string;
  gitRef?: string;
  gitCommit?: string;
};
