export const browserCoreExamples = [
  "joopo browser status",
  "joopo browser start",
  "joopo browser start --headless",
  "joopo browser stop",
  "joopo browser tabs",
  "joopo browser open https://example.com",
  "joopo browser focus abcd1234",
  "joopo browser close abcd1234",
  "joopo browser screenshot",
  "joopo browser screenshot --full-page",
  "joopo browser screenshot --ref 12",
  "joopo browser snapshot",
  "joopo browser snapshot --format aria --limit 200",
  "joopo browser snapshot --efficient",
  "joopo browser snapshot --labels",
];

export const browserActionExamples = [
  "joopo browser navigate https://example.com",
  "joopo browser resize 1280 720",
  "joopo browser click 12 --double",
  "joopo browser click-coords 120 340",
  'joopo browser type 23 "hello" --submit',
  "joopo browser press Enter",
  "joopo browser hover 44",
  "joopo browser drag 10 11",
  "joopo browser select 9 OptionA OptionB",
  "joopo browser upload /tmp/joopo/uploads/file.pdf",
  'joopo browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "joopo browser dialog --accept",
  'joopo browser wait --text "Done"',
  "joopo browser evaluate --fn '(el) => el.textContent' --ref 7",
  "joopo browser console --level error",
  "joopo browser pdf",
];
